### PR TITLE
[AMORO-2180]: Remove existed database/table check when delete external catalog

### LINKED ISSUE #2180: [Bug]: I encountered an error when deleting a non-empty external catalog.
### What happened?

image

### Affects Versions

matser

### What engines are you seeing the problem on?

AMS

### How to reproduce

Create a external catalog with table then remove it

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by shidayang**
## Why are the changes needed?
Close #2180 .

## Brief change log
- Remove the check logic in CatalogController

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/CatalogController.java [hunk 1]
```diff
@@ -503,13 +501,8 @@ public void catalogDeleteCheck(Context ctx) {
   public void deleteCatalog(Context ctx) {
     String catalogName = ctx.pathParam("catalogName");
     Preconditions.checkArgument(StringUtils.isNotEmpty(ctx.pathParam("catalogName")), "Catalog name is empty!");
-    List<String> dbs = tableService.listDatabases(catalogName);
```
Comment (wangtaohz) [inline ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/CatalogController.java:506]: We should check whether the catalog is an external catalog, and only the external catalog can skip the checking before dropping it from AMS.

**Review by zhoujinsong — APPROVED** [review]
LGTM.
