### PR TITLE
[AMORO-2295]: Fix the table property `watermark.base` conflict for keyed-table

### LINKED ISSUE #2295: [Bug]: Failed to get table properties when base store contain property `watermark.base`
### What happened?

Failed to get table properties when base store contain property `watermark.base`

### Affects Versions

master

### What engines are you seeing the problem on?

Core

### How to reproduce

image

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by baiyangtx**
## Why are the changes needed?
 

Close #2295.

## Brief change log 

- Using hash map instead of ImmutableMap.Builder for KeyedTable.properties()

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [X] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (  no)

### CODE REVIEW

File: core/src/main/java/com/netease/arctic/table/BasicKeyedTable.java [hunk 1]
```diff
@@ -18,6 +18,7 @@
 
 package com.netease.arctic.table;
 
+import com.google.common.collect.Maps;
```
Comment (wangtaohz) [inline core/src/main/java/com/netease/arctic/table/BasicKeyedTable.java:21]: Nit: Use the `org.apache.iceberg.relocated.com.google.xxx`.

Comment (baiyangtx) [reply core/src/main/java/com/netease/arctic/table/BasicKeyedTable.java]: fixed

**Review by wangtaohz — APPROVED** [review]
LGTM
