### PR TITLE
[AMORO-1898] fix Mixed Hive Table's self-optimizing moving files to the stale hive table/partition location

### LINKED ISSUE #1898: [Bug]: If the optimizing of a Mixed Hive table fails to alter the Hive location, the files will be moved to the old Hive location.
### What happened?

When optimizing the Mixed Hive Format table but failing to alter the hive location,  the following full-optimizing will move files to the old Hive location. This brings two problems
- If the asynchronous thread successfully alters the Hive location, users will see a decrease in the data in Hive, similar to phantom reads.
- The commit of the following full-optimizing will fail, because the old hive location contains a mixture of files from new and old snapshots. The exception will be like

image

### Affects Versions

0.5.x,0.4.x,0.3.x

### What engines are you seeing the problem on?

Core

### How to reproduce

This issue occurs only when failing to alter the Hive location.

To reproduce this scenario
1. We can deliberately change the hive location back to its original location after the full-optimizing committing. 
2. Then insert some data, and wait for the next full-optimizing move files to the old hive location.
3. Then trigger another full-optimizing, it will fail when committing.

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wangtaohz**
## Why are the changes needed?

Close #1898.

## Brief change log

- move files to the location stored in iceberg properties instead of to the hive location
- support check and fix hive location before committing

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

File: hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java [hunk 1]
```diff
@@ -55,13 +58,16 @@
...
+import java.util.HashSet;
 import java.util.List;
 import java.util.Map;
 import java.util.Objects;
+import java.util.Set;
 import java.util.stream.Collectors;
 
 /**
- * Synchronize the metadata of the hive table to arctic table
+ * Utils for sync the metadata(schema/data) of the hive table to arctic table or sync data of arctic table to hive table
```
Comment (zhoujinsong) [inline hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java:70]:
```suggestion
 * Utils for syncing the metadata between the hive table and the arctic table.
```

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/UnKeyedTableCommit.java [hunk 2]
```diff
@@ -105,41 +109,60 @@ protected List<DataFile> moveFile2HiveIfNeed() {
...
+      String hiveSubdirectory = table.isKeyedTable() ?
+          HiveTableUtil.newHiveSubdirectory(maxTransactionId) : HiveTableUtil.newHiveSubdirectory();
+
+      Partition p = HivePartitionUtil.getPartition(hiveClient, table, partitionValues);
+      if (p == null) {
+        return HiveTableUtil.newHiveDataLocation(((SupportHive) table).hiveLocation(),
+            table.spec(), targetFile.partition(), hiveSubdirectory);
+      } else {
+        return p.getSd().getLocation();
+      }
```
Comment (baiyangtx) [inline ams/server/src/main/java/com/netease/arctic/server/optimizing/UnKeyedTableCommit.java:150]: Does it seem like there might be a performance issue if HMSClient.getPartition() needs to be called for each DataFile?

File: hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java [hunk 3]
```diff
@@ -222,6 +228,207 @@ public static void syncHiveDataToArctic(SupportHive table, HMSClientPool hiveCli
     }
   }
 
+  /**
+   * Synchronize the data change of the arctic table to hive table
+   * @param table support hive table
+   */
+  public static void syncArcticDataToHive(SupportHive table) {
+    UnkeyedTable baseStore;
+    if (table.isKeyedTable()) {
```
Comment (baiyangtx) [inline hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java:237]: Should this method be in HiveDataSynchronizer ?

Is there some unit test for this method?

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/UnKeyedTableCommit.java (hunk 2 above)
Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/optimizing/UnKeyedTableCommit.java:150]: The `computeIfAbsent` is trying to avoid the performance issue.
```
String partitionPath = partitionPathMap.computeIfAbsent(taskRuntime.getPartition(),
            key -> getPartitionPath(hiveClient, maxTransactionId, targetFile, partitionSchema));
```

File: hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java (hunk 3 above)
Comment (wangtaohz) [reply hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java:237]: I don't think we have a class named `HiveDataSynchronizer` now, and the `HiveMetaSynchronizer` contains both methods `syncHiveSchemaToArctic` and `syncHiveDataToArctic`, which means `Schema` and `Data` are both kinds of `Meta`.

The unit test class is in the module `ams/server` which is `TestHiveCommitSync`, I will move it to module `hive`.

Comment (baiyangtx) [reply hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java:237]: Is the integration test under the ams/server module? Should additional unit tests be added specifically for this method?

Comment (wangtaohz) [reply hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java:237]: Not the integration test, it‘s a specialized test class for syncing Amoro data to Hive.

**Review by baiyangtx — APPROVED** [review]
LGTM, Thanks a lot for your contribution.
