### PR TITLE
[AMORO-1802] Fix optimizing tasks failed to retry

### LINKED ISSUE #1802: [Bug]: Optimizing process hung up and some optimizing tasks are in `PLANNED` status
### What happened?

Occasionally, the optimizing process may hang up during `Running`. At this time, some tasks have been completed while others remain in the `PLANNED` status.

### Affects Versions

0.5.0

### What engines are you seeing the problem on?

_No response_

### How to reproduce

It's an occasional issue, but the optimizing hang-up occurred after this error when connecting to sysdb.

image

### Relevant log output

_No response_

### Anything else

some other error message

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wangtaohz**
## Why are the changes needed?

fix #1802 

## Brief change log

  - fix the task is not offered to the `retryQueue` if polling fails
  - put tasks back to `executingTaskMap` if reset fails when `checkSuspending`
  - remove useless field `next` from `TaskStatusMachine`
  - add some logs for optimizing

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

File: ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java [hunk 1]
```diff
@@ -130,17 +130,18 @@ public void touch(String authToken) {
 
   @Override
   public OptimizingTask pollTask(String authToken, int threadId) {
+    LOG.debug("Optimizer {} threadId={} pooling task", authToken, threadId);
```
Comment (zhoujinsong) [inline ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java:133]: We should pay attention to syntax errors in log printing.

The log message here can be `Optimizer {} (thread id {}) try polling task`

File: ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java [hunk 2]
```diff
@@ -130,17 +130,18 @@ public void touch(String authToken) {
...
     OptimizingQueue queue = getQueueByToken(authToken);
     OptimizingTask task = queue.pollTask(authToken, threadId);
     if (task != null) {
-      LOG.info("Optimizer {} polling task {}", authToken, task.getTaskId());
+      LOG.info("Optimizer {} threadId={} polling task {}", authToken, threadId, task.getTaskId());
```
Comment (zhoujinsong) [inline ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java:137]: And log message here can be `Optimizer {} (thread id {})  polled task {}`

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java [hunk 3]
```diff
@@ -179,7 +180,8 @@ private void safelySchedule(TaskRuntime task, OptimizingThread thread) {
     try {
       task.schedule(thread);
     } catch (Throwable throwable) {
-      retryTask(task, false);
+      LOG.error("Schedule task {} failed, put it to retryQueue", task.getTaskId(), throwable);
```
Comment (zhoujinsong) [inline ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java:183]: Do not use a parameter name like `retryQueue` when printing log.

File: ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java (hunk 1 above)
Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java:133]: Ok, I will modify it.

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java (hunk 3 above)
Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java]: OK, I modified it.
