### PR TITLE
[AMORO-2196] Fix scale out error

### LINKED ISSUE #2196: [Bug]: Flink optimizer scales out interaction error
### What happened?

I wanna scale out a flink optimizer in a ready resource group, but occur timeout:
截屏2023-10-26 20 22 25

Actually, it starts successfully:
截屏2023-10-26 20 47 44

And I can not release it either.

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

Just scale out a flink optimizer.

### Relevant log output

```shell
No error log
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by HuangFru**
## Why are the changes needed?

Close #2196.

## Brief change log

- Break out of the loop when the value is successfully fetched.
- Remove useless 'fetch' for 'releaseOptimizer'.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Review by shidayang — APPROVED** [review]

**Comment by shidayang** [comment]
LGTM

**Comment by shidayang** [comment]
Is it convenient to add unit tests in this place?

**Comment by HuangFru** [comment]
> Is it convenient to add unit tests in this place?

File: ams/server/src/main/java/com/netease/arctic/server/manager/FlinkOptimizerContainer.java [hunk 1]
```diff
@@ -285,8 +285,8 @@ private <T> T fetchCommandOutput(Process exec, Function<String, T> commandReader
             break;
           }
           LOG.info("{}", readLine);
-          if (commandReader != null) {
-            value = commandReader.apply(readLine);
+          if ((value = commandReader.apply(readLine)) != null) {
```
Comment (zhoujinsong) [inline ams/server/src/main/java/com/netease/arctic/server/manager/FlinkOptimizerContainer.java:288]: We should keep the null check on `commandReader` to avoid throwing NPE exceptions.

**Review by zhoujinsong — COMMENTED** [review]
@HuangFru I left some coments.

File: ams/server/src/main/java/com/netease/arctic/server/manager/FlinkOptimizerContainer.java (hunk 1 above)
Comment (HuangFru) [reply ams/server/src/main/java/com/netease/arctic/server/manager/FlinkOptimizerContainer.java:288]: There should be no NPE here.
