### PR TITLE
[AMORO-2324] Use 'DateTimeFormatter' to avoid format parsing exceptions in multithreading

### LINKED ISSUE #2324: [Bug]: `com.netease.arctic.utils.ArcticDataFiles.readHoursData` use `SimpleDateFormat` Parsing errors will occur under multi-threading
### What happened?

`com.netease.arctic.utils.ArcticDataFiles.readHoursData` use `SimpleDateFormat` Parsing errors will occur under multi-threading

### Affects Versions

master

### What engines are you seeing the problem on?

ams
### How to reproduce

Increasing the number of Refresh threads will cause them to appear more frequently.

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by huyuanfeng2018**
…ns in multithreading

## Why are the changes needed?

Close #2324 .

## Brief change log

-Use 'DateTimeFormatter' to avoid format parsing exceptions in multithreading

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java [hunk 1]
```diff
@@ -12,22 +12,18 @@
...
 import java.util.Arrays;
-import java.util.Date;
 import java.util.List;
-import java.util.TimeZone;
 import java.util.UUID;
 import java.util.stream.Collectors;
 
 public class ArcticDataFiles {
-  public static final OffsetDateTime EPOCH = Instant.ofEpochSecond(0).atOffset(ZoneOffset.UTC);
-  public static final SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd-hh");
```
Comment (wangtaohz) [inline core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java:30]: The previous code used 'hh' to parse the hour, which may cause other bugs. 

I will test and evaluate the impact of this fix and determine whether it needs to be merged into versions 0.5.x and 0.6.x.

**Review by wangtaohz — APPROVED** [review]
LGTM

File: core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java (hunk 1 above)
Comment (huyuanfeng2018) [reply core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java:30]: > The previous code used 'hh' to parse the hour, which may cause other bugs.
> 
> I will test and evaluate the impact of this fix and determine whether it needs to be merged into versions 0.5.x and 0.6.x.

There should be no impact. There is no distinction between hh and HH in `SimpleDateFormat`, and both will be regarded as 24-hour format.

Comment (wangtaohz) [reply core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java:30]: I have built a corner case, when hour = 12.

```java
  public static void main(String[] args) throws ParseException {
    SimpleDateFormat sdf_hh = new SimpleDateFormat("yyyy-MM-dd-hh");
    sdf_hh.setTimeZone(TimeZone.getTimeZone("UTC"));
    Date date_hh = sdf_hh.parse("2022-08-08-12");
    System.out.println("date_hh = " + date_hh);

    SimpleDateFormat sdf_HH = new SimpleDateFormat("yyyy-MM-dd-HH");
    sdf_HH.setTimeZone(TimeZone.getTimeZone("UTC"));
    Date date_HH = sdf_HH.parse("2022-08-08-12");
    System.out.println("date_HH = " + date_HH);
  }
```
output
```
date_hh = Mon Aug 08 08:00:00 CST 2022
date_HH = Mon Aug 08 20:00:00 CST 2022
```

Comment (wangtaohz) [reply core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java:30]: I can be reproduced by changing the unit test case `com.netease.arctic.utils.TestArcticDataFiles#testHoursPartition`.

image

Comment (huyuanfeng2018) [reply core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java:30]: It seems true. yyyy-MM-dd-hh cannot parse the case where hour is 12. You need to specify AM or PM. If not specified, it will be parsed to midnight by default.
Then the previous logic is actually wrong.

Comment (huyuanfeng2018) [reply core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java:30]: We should fix this bug immediately, is a backport required?

Comment (wangtaohz) [reply core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java:30]: Yes, I will help to cherry-pick to 0.5.x and 0.6.x after merging to master.

**Review by baiyangtx — COMMENTED** [review]
This method seems to be the core code. Can unit tests be supplemented to support long-term maintenance of this feature?

**Comment by huyuanfeng2018** [comment]
> This method seems to be the core code. Can unit tests be supplemented to support long-term maintenance of this feature?

done.

**Comment by wangtaohz** [comment]
Close #2334

**Review by baiyangtx — APPROVED** [review]
LGTM
