### PR TITLE
[AMORO-1807] When I upgrade a hive table and it fails, it deletes the original hive table

### LINKED ISSUE #1807: [Bug]: When I upgrade a hive table and it fails, it deletes the original hive table.
### What happened?

First I upgraded a hive table to a mixed hive table.
image
image
You can tell I failed at this step.
image
However when I refreshed the page to load the table it no longer existed, later I went to hms to check that the table had been deleted before.
image

### Affects Versions

master

### What engines are you seeing the problem on?

Core, AMS

### How to reproduce

1. Create a hive table and upgrade it, and let it fail.
2. Check the hive table

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nicochen**
## Why are the changes needed?

fix #1807 

## Brief change log
Added a logic that deletes the hive table, but does not delete the amoro table

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: hive/src/main/java/com/netease/arctic/hive/catalog/MixedHiveTables.java [hunk 1]
```diff
@@ -247,6 +247,10 @@ public void dropTableByMeta(TableMeta tableMeta, boolean purge) {
     }
   }
 
+  public void dropTableMetaButNotDropHiveTable(TableMeta tableMeta) {
```
Comment (zhoujinsong) [inline hive/src/main/java/com/netease/arctic/hive/catalog/MixedHiveTables.java:250]: Does this method appear to be necessary?
You can just call `MixedTables#dropTableByMeta` directly.

**Review by zhoujinsong — APPROVED** [review]
LGTM. Thanks a lot for your contribution.
