### PR TITLE
[AMORO-2117] Support Http interface for getting details of optimizing tasks

### LINKED ISSUE #2117: [Subtask]: Supports Http interface for getting details of optimizing tasks
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

The tasks are the most important part for the detail page of optimizing process.

We should support Http interface to get tasks of an optimizing process, which should support `page` and `pageSize`.

All the information of tasks are stored in the table `task_runtime` of sysdb
```
CREATE TABLE `task_runtime` (
  `process_id` bigint(20) NOT NULL,
  `task_id` int(11) NOT NULL,
  `retry_num` int(11) DEFAULT NULL COMMENT 'Retry times',
  `table_id` bigint(20) NOT NULL,
  `partition_data` varchar(128) DEFAULT NULL COMMENT 'Partition data',
  `create_time` timestamp NULL DEFAULT NULL COMMENT 'Task create time',
  `start_time` timestamp NULL DEFAULT NULL COMMENT 'Time when task start waiting to execute',
  `end_time` timestamp NULL DEFAULT NULL COMMENT 'Time when task finished',
  `cost_time` bigint(20) DEFAULT NULL,
  `status` varchar(16) DEFAULT NULL COMMENT 'Optimize Status: PLANNED, SCHEDULED, ACKED, FAILED, SUCCESS, CANCELED',
  `fail_reason` varchar(4096) DEFAULT NULL COMMENT 'Error message after task failed',
  `optimizer_token` varchar(50) DEFAULT NULL COMMENT 'Job type',
  `thread_id` int(11) DEFAULT NULL COMMENT 'Job id',
  `rewrite_output` longblob COMMENT 'rewrite files output',
  `metrics_summary` text COMMENT 'metrics summary',
  `properties` mediumtext COMMENT 'task properties',
  PRIMARY KEY (`process_id`,`task_id`),
  KEY `table_index` (`table_id`,`process_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Optimize task basic information'
```

This issue is related to #2115

### Parent issue

#2114

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongqishang**
## Why are the changes needed?

Close #2117.

## Brief change log

- Add new interface `/tables/catalogs/{catalog}/dbs/{db}/tables/{table}/optimizing-processes/{processId}/tasks`

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

```
{
    "message": "success",
    "code": 200,
    "result": {
        "list": [
            {
                "tableId": 1351,
                "processId": 1698840207040,
                "taskId": 1,
                "partitionData": "",
                "status": "SUCCESS",
                "retryNum": 0,
                "threadId": 0,
                "startTime": 1698840208000,
                "endTime": 1698840214000,
                "costTime": 12038,
                "failReason": null,
                "summary": {
                    "newFileSize": 5148771,
                    "newFileCnt": 1,
                    "rewriteDataSize": 5338697,
                    "rewritePosDataSize": 0,
                    "equalityDeleteSize": 24091,
                    "positionalDeleteSize": 1849,
                    "rewriteDataFileCnt": 7,
                    "reRowDeletedDataFileCnt": 0,
                    "eqDeleteFileCnt": 6,
                    "posDeleteFileCnt": 1
                },
                "properties": {
                    "task-executor-factory-impl": "com.netease.arctic.optimizing.IcebergRewriteExecutorFactory"
                }
            }
        ],
        "total": 31
    }
}
```
## Documentation

- Does this pull request introduce a new feature? (**yes** / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/DashboardServer.java [hunk 1]
```diff
@@ -186,6 +186,9 @@ public EndpointGroup endpoints() {
             get(
                 "/tables/catalogs/{catalog}/dbs/{db}/tables/{table}/optimizing-processes",
                 tableController::getOptimizingProcesses);
+            get(
+                "/tables/catalogs/{catalog}/dbs/{db}/tables/{table}/optimizing-processes/{processId}/detail",
```
Comment (wangtaohz) [inline ams/server/src/main/java/com/netease/arctic/server/dashboard/DashboardServer.java:190]: Maybe the Http API can be changed to `/tables/catalogs/{catalog}/dbs/{db}/tables/{table}/optimizing-processes/{processId}/tasks`, because this API is supposed to return a list of optimizing task informations.

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/FormatTableDescriptor.java [hunk 2]
```diff
@@ -59,6 +60,10 @@ public interface FormatTableDescriptor {
   Pair<List<OptimizingProcessInfo>, Integer> getOptimizingProcessesInfo(
       AmoroTable<?> amoroTable, int limit, int offset);
 
+  /** Get the paged optimizing process detail information of the {@link AmoroTable}. */
+  List<OptimizingProcessDetailInfo> getOptimizingProcessDetailInfo(
```
Comment (wangtaohz) [inline ams/server/src/main/java/com/netease/arctic/server/dashboard/FormatTableDescriptor.java:64]: The method can be renamed to `getOptimingTaskInfos`, and the class `OptimizingProcessDetailInfo` renamed to `OptimizingTaskInfo`.

**Review by wangtaohz — COMMENTED** [review]
I provided some suggestions on interface naming, please task a look. @zhongqishang

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/DashboardServer.java (hunk 1 above)
Comment (zhongqishang) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/DashboardServer.java]: Done.

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/FormatTableDescriptor.java (hunk 2 above)
Comment (zhongqishang) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/FormatTableDescriptor.java]: Done.

**Review by wangtaohz — APPROVED** [review]
LGTM!
