### PR TITLE
[Hotfix] Cannot construct instance of Jsonnode when doing login

### LINKED ISSUE #2654: [Bug]: Cannot construct instance of Jsonnode when doing login
### What happened?

when I performed login action, the following error was caught:
`│ amoro-ams com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.apache.paimon.shade.jackson2.com.fasterxml.jackson.databind.JsonNode` (no Cre │
│ amoro-ams  at [Source: (String)"{"user":"admin","password":"admin"}"; line: 1, column: 1]`

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

_No response_

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tcodehuber**
## Why are the changes needed?

Close #2654.

## Brief change log

- Discard import shade class of jackson in `com.netease.arctic.server.dashboard.controller` package,  maybe there are conflicting between javalin's default jsonmapper and shade class.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/OptimizerController.java [hunk 1]
```diff
@@ -114,7 +114,7 @@ public void getOptimizers(Context ctx) {
         optimizerList.stream()
             .map(
                 e -> {
-                  ObjectNode jsonObject = (ObjectNode) JacksonUtil.fromObjects(e);
+                  ObjectNode jsonObject = new ObjectMapper().valueToTree(e);
```
Comment (zhoujinsong) [inline ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/OptimizerController.java:117]: We should import the shaded classes as much as possible, so it's best to construct a POJO for the optimizer instance.

**Review by zhoujinsong — COMMENTED** [review]
@tcodehuber Thanks a lot for fixing that!
I left a comment, PTAL.

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/OptimizerController.java (hunk 1 above)
Comment (XBaith) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/OptimizerController.java:117]: > We should import the shaded classes as much as possible, so it's best to construct a POJO for the optimizer instance.

Make sense, I also suggest append the optimier token and display it on webpage, it can help us identifier optimizers

Comment (zhoujinsong) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/OptimizerController.java:117]: LGTM.

Comment (tcodehuber) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/OptimizerController.java]: Thanks for your comments. Plz have a look again.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

Thanks a lot for the quick fixing.

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizerInstanceInfo.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.netease.arctic.server.dashboard.model;
+
+import com.netease.arctic.server.resource.OptimizerInstance;
+
+public class OptimizerInstanceInfo extends OptimizerInstance {
```
Comment (XBaith) [inline ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizerInstanceInfo.java:23]: The "OptimizerInstanceInfo" is just a DTO for AMS, so I don't think it should extend "Resouce". Also there are some duplicate params

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizerInstanceInfo.java [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+  }
+
+  public String getContainer() {
+    return container;
+  }
+
+  public void setContainer(String container) {
+    this.container = container;
+  }
+}
```
Comment (XBaith) [inline ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizerInstanceInfo.java:83]: It's better to overwrite equals and hascode method

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizerInstanceInfo.java (hunk 2 above)
Comment (XBaith) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizerInstanceInfo.java:23]: There are 9 parameters in there, and we can add a generator class to make it clear to add the field:
```
    List<OptimizerInfo> result =
        optimizerList.stream()
            .map(
                e ->
                    OptimizerInfo.builder()
                        .token(e.getToken())
                        .startTime(e.getStartTime())
                        .touchTime(e.getTouchTime())
                        .jobId(e.getResourceId())
                        .optimizerGroup(e.getGroupName())
                        .coreNumber(e.getThreadCount())
                        .memory(e.getMemoryMb())
                        .jobStatus("RUNNING")
                        .container(e.getContainerName())
                        .build())
            .collect(Collectors.toList());
```

Comment (zhoujinsong) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizerInstanceInfo.java:23]: Yes, we may do better to make the DTO much simpler.

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizerInstanceInfo.java [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+ */
+
+package com.netease.arctic.server.dashboard.model;
+
+import com.netease.arctic.server.resource.OptimizerInstance;
+
+public class OptimizerInstanceInfo extends OptimizerInstance {
+  private String jobId;
+
+  private String optimizerGroup;
```
Comment (XBaith) [inline ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizerInstanceInfo.java:26]: Front site will catch `groupName` instead of `optimizerGroup`

**Comment by tcodehuber** [comment]
@XBaith @zhoujinsong code refactor has been committed again, PTAL.

**Review by XBaith — APPROVED** [review]
