### PR TITLE
[AMORO-2302]: Donot trigger optimizing for mixed iceberg table store in Iceberg catalog.

### LINKED ISSUE #2302: [Bug]:  The "change store" was mistakenly triggered for optimization.
### What happened?

The "change store" was independently triggered for optimizing, resulting in duplicate data on the mixed-iceberg table.

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

Creating a mixed-iceberg catalog of type "hive" and then creating an iceberg catalog of type "hive." 

After creating a table under the mixed-iceberg catalog, two independent iceberg tables will be visible under the iceberg catalog. 

At this point, mistakenly triggering optimization on both iceberg tables will occur.

be4abcf3aadeb54b7d0ab140f7f77f3

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by baiyangtx**
## Why are the changes needed? 

Close #2302.

## Brief change log
 
- Ignore Iceberg if it is a table store of mixed-iceberg when sync table in external catalog

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [X] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? ( no)

### CODE REVIEW

File: ams/server/src/main/java/com/netease/arctic/server/table/DefaultTableService.java [hunk 1]
```diff
@@ -622,6 +623,11 @@ private boolean handleTableRuntimeAdded(
             tableIdentity.getDatabase(), tableIdentity.getTableName());
     AmoroTable<?> table =
         externalCatalog.loadTable(tableIdentity.getDatabase(), tableIdentity.getTableName());
+    if (TableFormat.ICEBERG == table.format()) {
```
Comment (wangtaohz) [inline ams/server/src/main/java/com/netease/arctic/server/table/DefaultTableService.java:626]: This would result in `table_identifier` having this table, but `table_runtime` and the `tableRuntimeMap` in memory do not have this table.

But I have checked the relevant codes, and it seems that it will not cause any issues. 👍

**Review by wangtaohz — APPROVED** [review]
LGTM.

File: core/src/main/java/com/netease/arctic/utils/TablePropertyUtil.java [hunk 2]
```diff
@@ -133,4 +134,19 @@ public static long getTableWatermark(Map<String, String> properties) {
...
     }
   }
+
+  /**
+   * Check if an iceberg table is a table store of a mixed-iceberg table.
+   *
+   * @param properties table properties of iceberg
+   * @return true if this it a table store.
+   */
+  public static boolean isMixedTableStore(Map<String, String> properties) {
```
Comment (wangtaohz) [inline core/src/main/java/com/netease/arctic/utils/TablePropertyUtil.java:144]: The Mixed Hive Format also has the same problem, and the unkeyed Mixed Format table should also be considered.

Comment (baiyangtx) [reply core/src/main/java/com/netease/arctic/utils/TablePropertyUtil.java:144]: The table store of mixed-hive will not be loaded by iceberg catalog
