### PR TITLE
[AMORO-2510] [Improvement]: add some flink runtime info for optimizer

### LINKED ISSUE #2510: [Improvement]: add some flink runtime info for optimizer
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

- Add container_id, application_id,host to the exception info of optimize task. like this 
image

- Add a metric for the total number of tasks processed in the optimize executor, and include `optimizeGroup` as a label for easier visualization. like this 
image

### How should we improve?

- Get TaskmanagerInfo through `getRuntimeContext().getTaskManagerRuntimeInfo().getConfiguration()`
- By registering a Counter type metric and adding the optimize_group label, the statistics will be output through Flink's metric mechanism. This is used to detect abnormal situations where certain Optimizers may not be functioning properly.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Aireed**
## Why are the changes needed?

Close #2510.

## Brief change log

- Get TaskmanagerInfo through getRuntimeContext().getTaskManagerRuntimeInfo().getConfiguration() and add info  to the fail message
- Add a metric for the total number of tasks processed in the optimize executor, and include optimizeGroup as a label for easier visualization

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

**Comment by czy006** [comment]
@Aireed Can you add this part of unit tests or related screenshots?

**Comment by zhongqishang** [comment]
@Aireed Thanks for your contribution.

Now, we support three deployment modes: `yarn-per-job`, `yarn-application`, `kubernetes-application`. I found that the kubernetes environment is not distinguished. The current logic will also be executed under kubernetes. 
Can we only execute it in the yarn environment?

`applicationId` is the value from the `high-availability.cluster-id` attribute. If the user does not enable **HA**, will it affect the execution of `FlinkExecutor`?

I did not obtain `taskmanager.resource-id` in my environment (Flink 1.14.4 + yarn application mode). I saw the official website description [1]. It is invalid under yarn?


[1]:https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/deployment/config/#taskmanager-resource-id

**Comment by Aireed** [comment]
> Now, we support three deployment modes: `yarn-per-job`, `yarn-application`, `kubernetes-application`. I found that the kubernetes environment is not distinguished. The current logic will also be executed under kubernetes. Can we only execute it in the yarn environment?
>
of course we can if the info is meaningless in k8s environment.  i have no k8s environment, could you have time to test it.  i will find some way to distinguish the environment.

 
> `applicationId` is the value from the `high-availability.cluster-id` attribute. If the user does not enable **HA**, will it affect the execution of `FlinkExecutor`?
> 
I have tested  this scenario before submitting the PR. Even if HA is not enabled, the property "high-availability.cluster-id" still exists.

> I did not obtain `taskmanager.resource-id` in my environment (Flink 1.14.4 + yarn application mode), I missing something? I saw the official website description [1](https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/deployment/config/#taskmanager-resource-id). It is invalid under yarn?

i will try it later.

@zhongqishang

**Comment by zhongqishang** [comment]
> > Now, we support three deployment modes: `yarn-per-job`, `yarn-application`, `kubernetes-application`. I found that the kubernetes environment is not distinguished. The current logic will also be executed under kubernetes. Can we only execute it in the yarn environment?
> 
> of course we can if the info is meaningless in k8s environment. i have no k8s environment, could you have time to test it. i will find some way to distinguish the environment.
> 

I test in my k8s env(Flink 1.14.4 + k8s 1.19), `TASK_MANAGER_RESOURCE_ID`, `HA_CLUSTER_ID` is normal, like below: 
```
TASK_MANAGER_RESOURCE_ID : {cluster id}-taskmanager-1-1, 
HA_CLUSTER_ID : {cluster id}
```
But I didn't find `HOST`.

> > `applicationId` is the value from the `high-availability.cluster-id` attribute. If the user does not enable **HA**, will it affect the execution of `FlinkExecutor`?
> 
> I have tested this scenario before submitting the PR. Even if HA is not enabled, the property "high-availability.cluster-id" still exists.
> 

Yes, it exists.

> > I did not obtain `taskmanager.resource-id` in my environment (Flink 1.14.4 + yarn application mode), I missing something? I saw the official website description [1](https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/deployment/config/#taskmanager-resource-id). It is invalid under yarn?
> 
> i will try it later.
> 
> @zhongqishang

My fault, it exists.

**Comment by Aireed** [comment]
cc @czy006 , this is the result of local test. PTAL.
Additionally, I have communicated offline with @zhongqishang  ,  and the information on the K8s environment is also ok and sufficient.

image

File: ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java [hunk 1]
```diff
@@ -26,30 +26,48 @@
...
+import java.util.Map;
+import java.util.concurrent.ConcurrentHashMap;
+import java.util.function.Consumer;
 
 public class OptimizerExecutor extends AbstractOptimizerOperator {
 
   private static final Logger LOG = LoggerFactory.getLogger(OptimizerExecutor.class);
 
   private final int threadId;
+  private Map<String, String> runtimeContext = new ConcurrentHashMap<String, String>();
```
Comment (zhoujinsong) [inline ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java:45]: I'm not sure if placing this logic in the `OptimizerExecutor` is a good approach; it seems that other types of optimizers currently don't require this logic. Can we consider migrating them to the `FlinkExecutor` instead?

File: ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java [hunk 2]
```diff
@@ -100,7 +118,16 @@ private boolean ackTask(OptimizingTask task) {
   }
 
   protected OptimizingTaskResult executeTask(OptimizingTask task) {
-    return executeTask(getConfig(), getThreadId(), task, LOG);
+    OptimizingTaskResult result = executeTask(getConfig(), getThreadId(), task, LOG);
+    // add optimizer flink runtime info, including application_id, tm_id, host
+    StringBuilder sb = new StringBuilder();
+    if (StringUtils.isNotEmpty(result.getErrorMessage())) {
```
Comment (zhoujinsong) [inline ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java:124]: I recommend replacing it with `com.google.common.base.Strings#isNullOrEmpty`.

**Review by zhoujinsong — COMMENTED** [review]
@Aireed Thanks a lot for your contribution!
I left some comments, PTAL.

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java [hunk 3]
```diff
@@ -18,26 +18,57 @@
...
     super.open();
     int subTaskIndex = getRuntimeContext().getIndexOfThisSubtask();
+    String taskManagerContainerId =
+        getRuntimeContext()
+            .getTaskManagerRuntimeInfo()
+            .getConfiguration()
+            .get(TASK_MANAGER_RESOURCE_ID);
+    String bindHost = getRuntimeContext().getTaskManagerRuntimeInfo().getConfiguration().get(HOST);
+    String applicationId =
+        getRuntimeContext().getTaskManagerRuntimeInfo().getConfiguration().getString(HA_CLUSTER_ID);
```
[the remark this answers is not in the document]
Comment (Aireed) [reply ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java:61]: > If high availability is not enabled, is it possible that a NPE occurs with this value?

NO. As mentioned above, my discussion with Zhong.  I have done the test , and  the code went well.

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java [hunk 4]
```diff
@@ -18,26 +18,57 @@
...
+  public FlinkExecutor(OptimizerExecutor[] allExecutors, String optimizeGroupName) {
+    this.allExecutors = allExecutors;
+    this.optimizeGroupName = optimizeGroupName;
+  }
+
   @Override
   public void open() throws Exception {
     super.open();
     int subTaskIndex = getRuntimeContext().getIndexOfThisSubtask();
+    String taskManagerContainerId =
```
Comment (zhongqishang) [inline ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java:54]: `Container` is a concept in Yarn. Flink has multiple deployment mode(Yarn,k8s). Maybe it is better to call it `taskManagerId`?

**Review by zhongqishang — COMMENTED** [review]
Thanks for your contribution, I left some comments.

File: ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java (hunk 1 above)
Comment (zhongqishang) [reply ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java:45]: I agree that the relevant logic of flink is only effective for flink.

Comment (zhongqishang) [inline ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java:45]:
```suggestion
  private final Map<String, String> runtimeContext = new ConcurrentHashMap<>();
```

File: ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java [hunk 5]
```diff
@@ -26,30 +26,48 @@
...
+import java.util.concurrent.ConcurrentHashMap;
+import java.util.function.Consumer;
 
 public class OptimizerExecutor extends AbstractOptimizerOperator {
 
   private static final Logger LOG = LoggerFactory.getLogger(OptimizerExecutor.class);
 
   private final int threadId;
+  private Map<String, String> runtimeContext = new ConcurrentHashMap<String, String>();
+  private Consumer metricsReporter = null;
```
Comment (zhongqishang) [inline ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java:46]:
```suggestion
  private Consumer<Integer> metricsReporter = null;
```

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+import com.netease.arctic.optimizer.common.OptimizerConfig;
+import com.netease.arctic.optimizer.common.OptimizerExecutor;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import java.util.Map;
+import java.util.concurrent.ConcurrentHashMap;
+import java.util.function.Consumer;
+
+/** @Auth: hzwangtao6 @Time: 2024/2/28 14:19 @Description: */
```
Comment (zhoujinsong) [inline ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java:33]: Can you add some description about the class in java doc rather than the author and time information.

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+public class FlinkOptimizerExecutor extends OptimizerExecutor {
+  private static final Logger LOG = LoggerFactory.getLogger(OptimizerExecutor.class);
+  private Map<String, String> runtimeContext = new ConcurrentHashMap<String, String>();
+  private Consumer<Integer> metricsReporter = null;
```
Comment (zhoujinsong) [inline ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java:37]: How about renaming the variable to `taskCounter` as it counts the task count. And I think you can use `org.apache.flink.metrics.Counter` directly here.

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+  public void callBeforeTaskComplete(OptimizingTaskResult result) {
+    if (metricsReporter != null) {
+      // reporter metrics by flink, counter the number of tasks consumed
+      metricsReporter.accept(1);
+    }
+  }
+
+  @Override
+  protected OptimizingTaskResult executeTask(OptimizingTask task) {
+    OptimizingTaskResult result = executeTask(getConfig(), getThreadId(), task, LOG);
```
Comment (zhoujinsong) [inline ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java:61]: How about replacing it with `super.executeTask(task)`.

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java [hunk 9]
```diff
@@ -18,26 +18,53 @@
...
 import org.apache.flink.streaming.api.operators.AbstractStreamOperator;
 import org.apache.flink.streaming.api.operators.OneInputStreamOperator;
 import org.apache.flink.streaming.runtime.streamrecord.StreamRecord;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 public class FlinkExecutor extends AbstractStreamOperator<Void>
     implements OneInputStreamOperator<String, Void> {
 
+  private static final Logger LOG = LoggerFactory.getLogger(FlinkExecutor.class);
```
Comment (zhoujinsong) [inline ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java:35]: It seems to bu unused.

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java [hunk 10]
```diff
@@ -18,26 +18,53 @@
...
   private final OptimizerExecutor[] allExecutors;
-  private OptimizerExecutor executor;
+  private FlinkOptimizerExecutor executor;
+  private String optimizeGroupName;
 
   public FlinkExecutor(OptimizerExecutor[] allExecutors) {
```
Comment (zhoujinsong) [inline ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java:40]: How about dropping this constructor if it is not needed any more?

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java (hunk 4 above)
Comment (zhoujinsong) [reply ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java:53]: +1

**Review by zhoujinsong — COMMENTED** [review]
@Aireed  I left some comments. PTAL.

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java (hunk 8 above)
Comment (Aireed) [reply ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java:61]: The last parameter of executeTask, LOG, is different from that of the parent class, so it cannot be replaced with super.execute(task) here.

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java (hunk 7 above)
Comment (Aireed) [reply ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java:37]: yep

File: ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java [hunk 11]
```diff
@@ -44,12 +44,16 @@ public OptimizerExecutor(OptimizerConfig config, int threadId) {
     this.threadId = threadId;
   }
 
+  // subclass can overwrite it to add some custome logic
+  public void callBeforeTaskComplete(OptimizingTaskResult result) {}
```
[the remark this answers is not in the document]
Comment (Aireed) [reply ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java]: yep

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java (hunk 6 above)
Comment (Aireed) [reply ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java]: done

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java (hunk 4 above)
Comment (Aireed) [reply ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java]: done

File: ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java (hunk 2 above)
Comment (Aireed) [reply ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java]: done

File: ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java (hunk 1 above)
Comment (Aireed) [reply ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java]: done

File: ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java [hunk 12]
```diff
@@ -0,0 +1,79 @@
...
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import java.util.Map;
+import java.util.concurrent.ConcurrentHashMap;
+
+/**
+ * OptimizerExecutor For flink engine only . 1、You can customize special execution logic for Flink
+ * here. 2、You can customize logic that will be called after task execution and before reporting
+ * task results to AMS.
```
Comment (zhoujinsong) [inline ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java:37]:
```suggestion
 * Optimizer executor For Flink engine supports:
 * <ul>
 * <li> Add additional content to error messages to help locate execution nodes.
 * <li> Add some Flink metrics like task number executed.
 * </ul>
```

Hi, I tried to polish the java doc here.

**Review by zhoujinsong — APPROVED** [review]
LGTM.
Thanks a lot for your contribution!
