### PR TITLE
[AMORO-1820]: Fix spark drop namespace error in rest catalog services.

### LINKED ISSUE #1820: [Bug]: terminal can't drop database
### What happened?

drop database under some  iceberg catalog
image

image

### Affects Versions

master

### What engines are you seeing the problem on?

Spark

### How to reproduce

drop database under some  iceberg catalog

### Relevant log output

```shell
drop database under some  iceberg catalog
```

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by baiyangtx**
## Why are the changes needed?

fix #1820 

## Brief change log

- Return empty list when listNamespace passes a database name

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [X] Run test locally before making a pull request

### CODE REVIEW

**Comment by baiyangtx** [comment]
image

checked

File: ams/server/src/main/java/com/netease/arctic/server/IcebergRestCatalogService.java [hunk 1]
```diff
@@ -137,10 +137,11 @@ public void handleException(Exception e, Context ctx) {
     jsonResponse(ctx, response);
     if (code.code >= 500) {
       LOG.warn("InternalServer Error", e);
+    } else {
```
Comment (zhoujinsong) [inline ams/server/src/main/java/com/netease/arctic/server/IcebergRestCatalogService.java:140]: Why do we need to reduce the logging level for errors in which the code is smaller than 500 here?

Comment (baiyangtx) [reply ams/server/src/main/java/com/netease/arctic/server/IcebergRestCatalogService.java:140]: because those errors happened when the client-side passed arguments with problems. 
The service side usually does not need to log those errors.

Comment (zhoujinsong) [reply ams/server/src/main/java/com/netease/arctic/server/IcebergRestCatalogService.java:140]: Got it.
Maybe add some comments here to tell that.

**Review by zhoujinsong — APPROVED** [review]
Validate in my local envrionment.
